[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
dotenvy = "0.15.7"
env_logger = "0.11.3"
log = "0.4.22"
once_cell = "1.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tokio = "1.38.0"

[dependencies.sqlx]
version = "0.7.4"
features = ["runtime-tokio", "uuid", "chrono", "postgres", "macros"]
